version: '3'

services:
  media_streamer:
    image: aler9/rtsp-simple-server:v1.3.0
    volumes:
      - /rtsp_camera/:/rtsp
    ports:
      - "8554:8554"

  rtsp_stream:
    image: jrottenberg/ffmpeg:4.4-alpine
    volumes:
      - ./rtsp_camera:/rtsp
    depends_on:
      - media_streamer
    entrypoint: ffmpeg -re -stream_loop -1 -i /rtsp/video.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://media_streamer:8554/stream


  # inference_app:
  #   build:
  #     context: .
  #     dockerfile: inference/Dockerfile
  #   volumes:
  #     - ./inference:/app
  #   ports:
  #       - "5000:5000"
    
